# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Github Action Test With Papermill
      env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SECRET_TEST: ${{ secrets.SECRET_TEST }}
      run: |
          papermill src/github_action.ipynb output/github_action.ipynb\
            -p SLACK_WEBHOOK_URL "$SLACK_WEBHOOK_URL"\
            -p SECRET_TEST "$SECRET_TEST"
        
